export interface Location {
  id: string;
  name: string;
  subtitle: string;
  lat: number;
  lon: number;
  county: string;
  province: string;
  tideStation: string;
  tideOffsetMinutes: number;
  metEireannStation?: string;
  saunaName?: string;
  saunaUrl?: string;
}

export const LOCATIONS: Location[] = [
  // Kerry
  {
    id: 'cromane',
    name: 'Cromane',
    subtitle: 'Co. Kerry · 52.11°N',
    lat: 52.105818, lon: -9.895735,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 25,
    metEireannStation: 'valentia',
    saunaName: "Samhradh's Sauna",
    saunaUrl: 'https://www.samhradhssauna.com/book-sauna',
  },
  {
    id: 'brandon-bay',
    name: 'Brandon Bay',
    subtitle: 'Co. Kerry · 52.14°N',
    lat: 52.141, lon: -10.268,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 10,
    metEireannStation: 'valentia',
    saunaName: 'Brandon Bay Sauna',
    saunaUrl: 'https://www.brandonbaysauna.com',
  },
  {
    id: 'dingle',
    name: 'Dingle',
    subtitle: 'Co. Kerry · 52.14°N',
    lat: 52.139, lon: -10.264,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 10,
    metEireannStation: 'valentia',
    saunaName: 'Gló Sauna',
    saunaUrl: 'https://glosaunas.ie/collections/all',
  },
  {
    id: 'ventry',
    name: 'Ventry',
    subtitle: 'Co. Kerry · 52.12°N',
    lat: 52.118, lon: -10.358,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 12,
    metEireannStation: 'valentia',
    saunaName: 'Sona Sauna',
    saunaUrl: 'https://linktr.ee/sonasauna',
  },
  {
    id: 'killarney',
    name: 'Killarney',
    subtitle: 'Co. Kerry · 52.06°N',
    lat: 52.059, lon: -9.504,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 20,
    metEireannStation: 'valentia',
    saunaName: 'Abhainn Sauna',
    saunaUrl: 'https://abhainnsauna.com/',
  },
  {
    id: 'glenteenassig',
    name: 'Glenteenassig',
    subtitle: 'Co. Kerry · 52.22°N',
    lat: 52.221, lon: -9.951,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 15,
    metEireannStation: 'valentia',
    saunaName: 'Acumeen Sauna',
    saunaUrl: 'https://flutterwbdev.azurewebsites.net/#/tenantDetails?tenantName=Acumeen_Farm',
  },
  {
    id: 'maharees',
    name: 'Maharees',
    subtitle: 'Co. Kerry · 52.27°N',
    lat: 52.268, lon: -10.018,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 8,
    metEireannStation: 'valentia',
    saunaName: 'Brandon Bay Sauna',
    saunaUrl: 'https://www.brandonbaysauna.com',
  },
  {
    id: 'ballybunion',
    name: 'Ballybunion',
    subtitle: 'Co. Kerry · 52.51°N',
    lat: 52.511, lon: -9.673,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 15,
    metEireannStation: 'valentia',
  },
  {
    id: 'banna-strand',
    name: 'Banna Strand',
    subtitle: 'Co. Kerry · 52.38°N',
    lat: 52.381, lon: -9.818,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 5,
    metEireannStation: 'valentia',
    saunaName: 'Happy Days Sauna',
    saunaUrl: 'https://happydayssauna.as.me/schedule/02db2acb',
  },
  {
    id: 'rossbeigh',
    name: 'Rossbeigh',
    subtitle: 'Co. Kerry · 52.06°N',
    lat: 52.062, lon: -9.972,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 22,
    metEireannStation: 'valentia',
    saunaName: 'Rossbeigh Sauna',
    saunaUrl: 'https://www.instagram.com/rossbeigh_sauna',
  },
  {
    id: 'cahersiveen',
    name: 'Cahersiveen',
    subtitle: 'Co. Kerry · 51.95°N',
    lat: 51.949, lon: -10.223,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 30,
    metEireannStation: 'valentia',
    saunaName: 'Skellig Sauna',
    saunaUrl: 'https://www.skelligsauna.ie',
  },
  {
    id: 'ballinskelligs',
    name: 'Ballinskelligs',
    subtitle: 'Co. Kerry · 51.82°N',
    lat: 51.819, lon: -10.270,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 32,
    metEireannStation: 'valentia',
    saunaName: 'Skellig Sauna',
    saunaUrl: 'https://www.skelligsauna.ie',
  },
  {
    id: 'derrynane',
    name: 'Derrynane',
    subtitle: 'Co. Kerry · 51.77°N',
    lat: 51.766, lon: -10.132,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 33,
    metEireannStation: 'valentia',
    saunaName: 'Kingdom Sauna',
    saunaUrl: 'https://www.kingdomsauna.ie',
  },
  {
    id: 'waterville',
    name: 'Waterville',
    subtitle: 'Co. Kerry · 51.83°N',
    lat: 51.829, lon: -10.168,
    county: 'Kerry', province: 'Munster',
    tideStation: 'Fenit', tideOffsetMinutes: 35,
    metEireannStation: 'valentia',
    saunaName: 'Fire & Ice',
    saunaUrl: 'https://www.fire-and-ice-sauna.com',
  },
  // Cork
  {
    id: 'kinsale',
    name: 'Kinsale',
    subtitle: 'Co. Cork · 51.70°N',
    lat: 51.706, lon: -8.527,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 15,
    metEireannStation: 'roches-point',
    saunaName: 'Wild Wellness',
    saunaUrl: 'https://www.wildwellness.ie',
  },
  {
    id: 'garrettstown',
    name: 'Garrettstown',
    subtitle: 'Co. Cork · 51.64°N',
    lat: 51.638, lon: -8.588,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 18,
    metEireannStation: 'roches-point',
    saunaName: 'Wild Wellness',
    saunaUrl: 'https://www.wildwellness.ie',
  },
  {
    id: 'inchydoney',
    name: 'Inchydoney',
    subtitle: 'Co. Cork · 51.60°N',
    lat: 51.598, lon: -8.862,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 30,
    metEireannStation: 'roches-point',
    saunaName: 'The Sauna Snugg',
    saunaUrl: 'https://www.thesaunasnugg.com',
  },
  {
    id: 'clonakilty',
    name: 'Clonakilty',
    subtitle: 'Co. Cork · 51.62°N',
    lat: 51.621, lon: -8.887,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 28,
    metEireannStation: 'roches-point',
    saunaName: 'Éalú Sauna',
    saunaUrl: 'https://www.ealusauna.ie',
  },
  {
    id: 'dunworley',
    name: 'Dunworley',
    subtitle: 'Co. Cork · 51.57°N',
    lat: 51.571, lon: -8.921,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 29,
    metEireannStation: 'roches-point',
    saunaName: 'Element Wellness',
    saunaUrl: 'https://www.elementwellness.ie',
  },
  {
    id: 'schull',
    name: 'Schull',
    subtitle: 'Co. Cork · 51.53°N',
    lat: 51.527, lon: -9.554,
    county: 'Cork', province: 'Munster',
    tideStation: 'Castletownbere', tideOffsetMinutes: 20,
    metEireannStation: 'sherkin-island',
    saunaName: 'The Balmy Barrel',
    saunaUrl: 'https://www.thebalmybarrel.com',
  },
  {
    id: 'fountainstown',
    name: 'Fountainstown',
    subtitle: 'Co. Cork · 51.79°N',
    lat: 51.793, lon: -8.294,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 5,
    metEireannStation: 'sherkin-island',
    saunaName: 'Happy Place Saunas',
    saunaUrl: 'https://happyplacesaunas.ie/book-now/',
  },
  {
    id: 'redbarn-youghal',
    name: 'Redbarn, Youghal',
    subtitle: 'Co. Cork · 51.93°N',
    lat: 51.932, lon: -7.856,
    county: 'Cork', province: 'Munster',
    tideStation: 'Cobh', tideOffsetMinutes: 10,
    metEireannStation: 'roches-point',
    saunaName: 'My Hot Spot – Sauna By The Sea',
    saunaUrl: 'https://flutterwbdev.azurewebsites.net/#/tenantDetails?tenantName=My_Hot_Spot',
  },
  // Clare
  {
    id: 'lahinch',
    name: 'Lahinch',
    subtitle: 'Co. Clare · 52.94°N',
    lat: 52.937, lon: -9.351,
    county: 'Clare', province: 'Munster',
    tideStation: 'Galway', tideOffsetMinutes: -30,
    metEireannStation: 'shannon',
  },
  {
    id: 'fanore',
    name: 'Fanore',
    subtitle: 'Co. Clare · 53.12°N',
    lat: 53.121, lon: -9.280,
    county: 'Clare', province: 'Munster',
    tideStation: 'Galway', tideOffsetMinutes: -20,
    metEireannStation: 'shannon',
  },
  // Galway
  {
    id: 'salthill',
    name: 'Salthill',
    subtitle: 'Co. Galway · 53.26°N',
    lat: 53.257, lon: -9.077,
    county: 'Galway', province: 'Connacht',
    tideStation: 'Galway', tideOffsetMinutes: 5,
    metEireannStation: 'athenry',
    saunaName: 'Sauna Fiáin',
    saunaUrl: 'https://www.saunafiain.com',
  },
  {
    id: 'spiddal',
    name: 'Spiddal',
    subtitle: 'Co. Galway · 53.24°N',
    lat: 53.243, lon: -9.308,
    county: 'Galway', province: 'Connacht',
    tideStation: 'Galway', tideOffsetMinutes: -5,
    metEireannStation: 'athenry',
    saunaName: 'Driftwood Sauna',
    saunaUrl: 'https://www.driftwoodsaunas.ie',
  },
  {
    id: 'dogs-bay',
    name: 'Dog\'s Bay',
    subtitle: 'Co. Galway · 53.38°N',
    lat: 53.383, lon: -9.982,
    county: 'Galway', province: 'Connacht',
    tideStation: 'Galway', tideOffsetMinutes: -15,
    metEireannStation: 'athenry',
    saunaName: 'Driftwood Sauna',
    saunaUrl: 'https://www.driftwoodsaunas.ie',
  },
  // Mayo
  {
    id: 'achill-island',
    name: 'Achill Island',
    subtitle: 'Co. Mayo · 53.96°N',
    lat: 53.961, lon: -10.070,
    county: 'Mayo', province: 'Connacht',
    tideStation: 'Ballyglass', tideOffsetMinutes: -10,
    metEireannStation: 'knock',
    saunaName: 'Sabhna Saunas',
    saunaUrl: 'https://www.sabhna.ie',
  },
  // Sligo
  {
    id: 'strandhill',
    name: 'Strandhill',
    subtitle: 'Co. Sligo · 54.27°N',
    lat: 54.271, lon: -8.604,
    county: 'Sligo', province: 'Connacht',
    tideStation: 'Ballyglass', tideOffsetMinutes: 20,
    metEireannStation: 'knock',
  },
  // Donegal
  {
    id: 'bundoran',
    name: 'Bundoran',
    subtitle: 'Co. Donegal · 54.47°N',
    lat: 54.474, lon: -8.281,
    county: 'Donegal', province: 'Ulster',
    tideStation: 'Ballyglass', tideOffsetMinutes: 25,
    metEireannStation: 'malin-head',
    saunaName: 'Salt & Ember',
    saunaUrl: 'https://www.saltandember.ie',
  },
  {
    id: 'rossnowlagh',
    name: 'Rossnowlagh',
    subtitle: 'Co. Donegal · 54.54°N',
    lat: 54.541, lon: -8.218,
    county: 'Donegal', province: 'Ulster',
    tideStation: 'Ballyglass', tideOffsetMinutes: 23,
    metEireannStation: 'malin-head',
    saunaName: 'Salt & Ember',
    saunaUrl: 'https://www.saltandember.ie',
  },
  {
    id: 'portnoo',
    name: 'Portnoo',
    subtitle: 'Co. Donegal · 54.83°N',
    lat: 54.834, lon: -8.493,
    county: 'Donegal', province: 'Ulster',
    tideStation: 'Aranmore', tideOffsetMinutes: 10,
    metEireannStation: 'malin-head',
    saunaName: 'Sliabh Liag Sauna',
    saunaUrl: 'https://www.sliabhliagsauna.ie',
  },
  {
    id: 'teelin',
    name: 'Teelin',
    subtitle: 'Co. Donegal · 54.63°N',
    lat: 54.632, lon: -8.637,
    county: 'Donegal', province: 'Ulster',
    tideStation: 'Aranmore', tideOffsetMinutes: 12,
    metEireannStation: 'malin-head',
    saunaName: 'Sliabh Liag Sauna',
    saunaUrl: 'https://www.sliabhliagsauna.ie',
  },
  {
    id: 'shrove',
    name: 'Shrove',
    subtitle: 'Co. Donegal · 55.22°N',
    lat: 55.222, lon: -7.036,
    county: 'Donegal', province: 'Ulster',
    tideStation: 'Aranmore', tideOffsetMinutes: 15,
    metEireannStation: 'malin-head',
    saunaName: 'The Sea View',
    saunaUrl: 'https://www.theseaviewsauna.ie',
  },
  // Dublin
  {
    id: 'portmarnock',
    name: 'Portmarnock',
    subtitle: 'Co. Dublin · 53.42°N',
    lat: 53.423, lon: -6.131,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 5,
    metEireannStation: 'dublin-airport',
    saunaName: 'Restore Sauna',
    saunaUrl: 'https://www.restoresauna.ie',
  },
  {
    id: 'portrane',
    name: 'Portrane',
    subtitle: 'Co. Dublin · 53.49°N',
    lat: 53.494, lon: -6.116,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 8,
    metEireannStation: 'dublin-airport',
    saunaName: 'The Sea Sauna',
    saunaUrl: 'https://www.theseasauna.ie',
  },
  {
    id: 'clontarf',
    name: 'Clontarf',
    subtitle: 'Co. Dublin · 53.37°N',
    lat: 53.367, lon: -6.198,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 3,
    metEireannStation: 'dublin-airport',
    saunaName: 'Fad Saoil Saunas',
    saunaUrl: 'https://www.fadsaoilsaunas.com',
  },
  {
    id: 'dollymount',
    name: 'Dollymount',
    subtitle: 'Co. Dublin · 53.37°N',
    lat: 53.371, lon: -6.157,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 4,
    metEireannStation: 'dublin-airport',
    saunaName: 'The Barrel Sauna',
    saunaUrl: 'https://www.thebarrelsauna.ie',
  },
  {
    id: 'sandycove',
    name: 'Sandycove',
    subtitle: 'Co. Dublin · 53.29°N',
    lat: 53.289, lon: -6.113,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: -2,
    metEireannStation: 'dublin-airport',
    saunaName: 'Fad Saoil Saunas',
    saunaUrl: 'https://www.fadsaoilsaunas.com',
  },
  {
    id: 'seapoint',
    name: 'Seapoint',
    subtitle: 'Co. Dublin · 53.30°N',
    lat: 53.296, lon: -6.156,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: -1,
    metEireannStation: 'dublin-airport',
    saunaName: 'Fad Saoil Saunas',
    saunaUrl: 'https://www.fadsaoilsaunas.com',
  },
  {
    id: 'killiney',
    name: 'Killiney',
    subtitle: 'Co. Dublin · 53.26°N',
    lat: 53.261, lon: -6.105,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: -3,
    metEireannStation: 'dublin-airport',
    saunaName: 'Sauna Tree',
    saunaUrl: 'https://www.saunatree.ie',
  },
  {
    id: 'howth',
    name: 'Howth',
    subtitle: 'Co. Dublin · 53.39°N',
    lat: 53.386, lon: -6.065,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 0,
    metEireannStation: 'dublin-airport',
    saunaName: 'Restore Sauna',
    saunaUrl: 'https://www.restoresauna.ie',
  },
  {
    id: 'skerries',
    name: 'Skerries',
    subtitle: 'Co. Dublin · 53.58°N',
    lat: 53.581, lon: -6.108,
    county: 'Dublin', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 10,
    metEireannStation: 'dublin-airport',
    saunaName: 'The Sea Sauna',
    saunaUrl: 'https://www.theseasauna.ie',
  },
  // Wicklow
  {
    id: 'greystones',
    name: 'Greystones',
    subtitle: 'Co. Wicklow · 53.14°N',
    lat: 53.141, lon: -6.063,
    county: 'Wicklow', province: 'Leinster',
    tideStation: 'Arklow', tideOffsetMinutes: -10,
    metEireannStation: 'dublin-airport',
    saunaName: 'Fad Saoil Saunas',
    saunaUrl: 'https://www.fadsaoilsaunas.com',
  },
  // Waterford
  {
    id: 'tramore',
    name: 'Tramore',
    subtitle: 'Co. Waterford · 52.16°N',
    lat: 52.159, lon: -7.146,
    county: 'Waterford', province: 'Munster',
    tideStation: 'Dunmore East', tideOffsetMinutes: 10,
    metEireannStation: 'johnstown-castle',
    saunaName: 'The Hot Pod',
    saunaUrl: 'https://www.thehotpod.ie',
  },
  {
    id: 'dunmore-east',
    name: 'Dunmore East',
    subtitle: 'Co. Waterford · 52.15°N',
    lat: 52.151, lon: -6.995,
    county: 'Waterford', province: 'Munster',
    tideStation: 'Dunmore East', tideOffsetMinutes: 0,
    metEireannStation: 'johnstown-castle',
    saunaName: 'The Hot Pod',
    saunaUrl: 'https://www.thehotpod.ie',
  },
  // Wexford
  {
    id: 'curracloe',
    name: 'Curracloe',
    subtitle: 'Co. Wexford · 52.39°N',
    lat: 52.392, lon: -6.385,
    county: 'Wexford', province: 'Leinster',
    tideStation: 'Arklow', tideOffsetMinutes: 20,
    metEireannStation: 'johnstown-castle',
    saunaName: 'The Sweathouse',
    saunaUrl: 'https://www.sweathouse.ie',
  },
  {
    id: 'cahore',
    name: 'Cahore',
    subtitle: 'Co. Wexford · 52.56°N',
    lat: 52.561, lon: -6.199,
    county: 'Wexford', province: 'Leinster',
    tideStation: 'Arklow', tideOffsetMinutes: 15,
    metEireannStation: 'johnstown-castle',
    saunaName: "Sybil's Sauna",
    saunaUrl: 'https://www.sybilssauna.ie',
  },
  // Louth
  {
    id: 'termonfeckin',
    name: 'Termonfeckin',
    subtitle: 'Co. Louth · 53.73°N',
    lat: 53.732, lon: -6.262,
    county: 'Louth', province: 'Leinster',
    tideStation: 'Howth', tideOffsetMinutes: 15,
    metEireannStation: 'dublin-airport',
    saunaName: 'An Ghrian Sauna',
    saunaUrl: 'https://www.anghriansauna.com',
  },
];

export const DEFAULT_LOCATION = LOCATIONS[0]; // Cromane

export function getLocationById(id: string): Location {
  return LOCATIONS.find(l => l.id === id) ?? DEFAULT_LOCATION;
}
