// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-saunas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/features/location/data/locations.ts
var LOCATIONS = [
  { id: "cromane", name: "Cromane", subtitle: "Co. Kerry \xB7 52.11\xB0N", lat: 52.1121, lon: -9.9042, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Samhradh's Sauna", saunaUrl: "https://samhradhssauna.com", country: "Ireland" },
  { id: "the-sea-view-sauna-shrove", name: "Shrove", subtitle: "Co. Donegal \xB7 55.23\xB0N", lat: 55.2272, lon: -6.9291, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "The Sea View Sauna", saunaUrl: "https://theseaviewsauna.ie", country: "Ireland" },
  { id: "ocean-waves-sauna-culdaff-beach", name: "Culdaff Beach", subtitle: "Co. Donegal \xB7 55.29\xB0N", lat: 55.2918, lon: -7.1453, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Ocean Waves Sauna", saunaUrl: "https://oceanwavessaunas.com", country: "Ireland" },
  { id: "the-swilly-sauna-rathmullan", name: "Rathmullan", subtitle: "Co. Donegal \xB7 55.10\xB0N", lat: 55.0953, lon: -7.5319, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "The Swilly Sauna", saunaUrl: "https://www.fresha.com/lvp/the-swilly-sauna-rathmullan-rwN88E", country: "Ireland" },
  { id: "cocoon-sauna-portnablagh-beach", name: "Portnablagh Beach", subtitle: "Co. Donegal \xB7 55.18\xB0N", lat: 55.1815, lon: -7.9277, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Cocoon Sauna", saunaUrl: "https://cocoonsauna.ie", country: "Ireland" },
  { id: "wild-atlantic-sea-sauna-dooey-beach", name: "Dooey Beach", subtitle: "Co. Donegal \xB7 54.88\xB0N", lat: 54.875, lon: -8.3853, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Wild Atlantic Sea Sauna", saunaUrl: "https://facebook.com/Wildatlanticseasaunadooeybeach", country: "Ireland" },
  { id: "the-hot-barrel-sauna-portsalon-pier", name: "Portsalon Pier", subtitle: "Co. Donegal \xB7 55.21\xB0N", lat: 55.2083, lon: -7.6187, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "The Hot Barrel Sauna", saunaUrl: "https://instagram.com/the_hot_barrel", country: "Ireland" },
  { id: "the-hot-barrel-sauna-kerrykeel-pier", name: "Kerrykeel Pier", subtitle: "Co. Donegal \xB7 55.15\xB0N", lat: 55.1451, lon: -7.6684, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "The Hot Barrel Sauna", saunaUrl: "https://instagram.com/the_hot_barrel", country: "Ireland" },
  { id: "itsaunatrailer-marble-hill", name: "Marble Hill", subtitle: "Co. Donegal \xB7 55.18\xB0N", lat: 55.1803, lon: -7.9014, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "ItSaunatrailer", saunaUrl: "https://www.itsaunatrailer.com/appointments", country: "Ireland" },
  { id: "sliabh-liag-sauna-teelin", name: "Teelin", subtitle: "Co. Donegal \xB7 54.62\xB0N", lat: 54.6234, lon: -8.6329, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Sliabh Liag Sauna", saunaUrl: "https://sliabhliagsauna.ie/products/teelin", country: "Ireland" },
  { id: "om-saunas-rossnowlagh-beach", name: "Rossnowlagh Beach", subtitle: "Co. Donegal \xB7 54.56\xB0N", lat: 54.5624, lon: -8.2153, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "OM Saunas", saunaUrl: "https://omsaunas.simplybook.it/v2/", country: "Ireland" },
  { id: "inishkeel-sauna-narin-strand-portnoo", name: "Narin Strand", subtitle: "Co. Donegal \xB7 54.84\xB0N", lat: 54.8421, lon: -8.4656, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Inishkeel Sauna", saunaUrl: "https://inishkeelsauna.ie", country: "Ireland" },
  { id: "salt-and-ember-sauna-boat-quay", name: "Boat Quay", subtitle: "Co. Donegal \xB7 54.48\xB0N", lat: 54.4769, lon: -8.289, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Salt and Ember Sauna", saunaUrl: "https://instagram.com/salt_and_ember", country: "Ireland" },
  { id: "salt-and-ember-sauna-creevy-pier", name: "Creevy Pier", subtitle: "Co. Donegal \xB7 54.53\xB0N", lat: 54.5301, lon: -8.2552, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Salt and Ember Sauna", saunaUrl: "https://instagram.com/salt_and_ember", country: "Ireland" },
  { id: "loughros-point-sauna-loughros-point", name: "Loughros Point", subtitle: "Co. Donegal \xB7 54.78\xB0N", lat: 54.7819, lon: -8.5407, county: "Donegal", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 10, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Loughros Point Sauna", saunaUrl: "https://facebook.com/profile.php?id=61562538052022", country: "Ireland" },
  { id: "blaze-it-sauna-mullaghmore-pier", name: "Mullaghmore Pier", subtitle: "Co. Sligo \xB7 54.47\xB0N", lat: 54.4661, lon: -8.4471, county: "Sligo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 20, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Blaze It Sauna", saunaUrl: "https://blazeitsauna.simplybook.it/v2/", country: "Ireland" },
  { id: "beo-by-the-sea-mullaghmore-pier", name: "Mullaghmore Pier", subtitle: "Co. Sligo \xB7 54.46\xB0N", lat: 54.4641, lon: -8.45, county: "Sligo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 20, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Beo By The Sea", saunaUrl: "https://beobythesea.com", country: "Ireland" },
  { id: "the-hot-box-sauna-rosses-point", name: "Rosses Point", subtitle: "Co. Sligo \xB7 54.31\xB0N", lat: 54.3067, lon: -8.5766, county: "Sligo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 20, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "The Hot Box Sauna", saunaUrl: "https://thehotboxsauna.ie/locations", country: "Ireland" },
  { id: "west-coast-sauna-enniscrone-pier", name: "Enniscrone Pier", subtitle: "Co. Sligo \xB7 54.22\xB0N", lat: 54.22, lon: -9.0959, county: "Sligo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 20, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "West Coast Sauna", saunaUrl: "https://instagram.com/westcoastsaunaireland", country: "Ireland" },
  { id: "sona-sauna-belmullet", name: "Belmullet", subtitle: "Co. Mayo \xB7 54.22\xB0N", lat: 54.2179, lon: -9.9904, county: "Mayo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 0, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Sona Sauna", saunaUrl: "https://instagram.com/sona.sauna.11", country: "Ireland" },
  { id: "sabhna-saunas-dugort-beach-achill", name: "Dugort Beach", subtitle: "Co. Mayo \xB7 54.01\xB0N", lat: 54.0124, lon: -10.0214, county: "Mayo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 0, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Sabhna Saunas", saunaUrl: "https://sabhna.ie", country: "Ireland" },
  { id: "sabhna-saunas-keel-beach-achill", name: "Keel Beach", subtitle: "Co. Mayo \xB7 53.97\xB0N", lat: 53.9728, lon: -10.0767, county: "Mayo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 0, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Sabhna Saunas", saunaUrl: "https://sabhna.ie", country: "Ireland" },
  { id: "the-wild-atlantic-sauna-old-head-beach", name: "Old Head Beach", subtitle: "Co. Mayo \xB7 53.78\xB0N", lat: 53.7783, lon: -9.7697, county: "Mayo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 0, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "The Wild Atlantic Sauna", saunaUrl: "https://thewildatlanticsauna.ie", country: "Ireland" },
  { id: "big-dipper-louisburgh", name: "Louisburgh", subtitle: "Co. Mayo \xB7 53.71\xB0N", lat: 53.7055, lon: -9.9017, county: "Mayo", province: "Connacht", tideStation: "Ballyglass", tideOffsetMinutes: 0, chartDatumOffset: 2.13, metEireannStation: "knock", saunaName: "Big Dipper", saunaUrl: "https://bigstyle.ie/bigdipper", country: "Ireland" },
  { id: "sweathouse-gurteen-pier", name: "Gurteen Pier", subtitle: "Co. Galway \xB7 53.60\xB0N", lat: 53.6022, lon: -9.9733, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Sweathouse", saunaUrl: "https://www.sweathouse.ie/bookings.html", country: "Ireland" },
  { id: "cois-tra-rugged-retreat-derrigimlagh", name: "Mannin Bay, Ballyconneely", subtitle: "Co. Galway \xB7 53.44\xB0N", lat: 53.4391, lon: -10.0765, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Cois Tra Rugged Retreat", saunaUrl: "https://ruggedretreat.ie", country: "Ireland" },
  { id: "oileanra-seaweed-baths-and-sauna-lettermullan", name: "Lettermullan", subtitle: "Co. Galway \xB7 53.24\xB0N", lat: 53.243, lon: -9.7167, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Oileanra Seaweed Baths and Sauna", saunaUrl: "https://oileanra.ie", country: "Ireland" },
  { id: "driftwood-sauna-spiddal-pier", name: "Spiddal Pier", subtitle: "Co. Galway \xB7 53.24\xB0N", lat: 53.2407, lon: -9.312, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Driftwood Sauna", saunaUrl: "https://www.driftwoodsauna.ie/appointments-4", country: "Ireland" },
  { id: "fad-saoil-saunas-salthill", name: "Salthill", subtitle: "Co. Galway \xB7 53.26\xB0N", lat: 53.2575, lon: -9.1041, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Fad Saoil Saunas", saunaUrl: "https://fadsaoilsaunas.ie", country: "Ireland" },
  { id: "sauna-fiain-renville-pier", name: "Renville Pier", subtitle: "Co. Galway \xB7 53.24\xB0N", lat: 53.2439, lon: -8.96733, county: "Galway", province: "Connacht", tideStation: "Galway", tideOffsetMinutes: 0, chartDatumOffset: 3.01, metEireannStation: "athenry", saunaName: "Sauna Fiain", saunaUrl: "https://saunafiain.com", country: "Ireland" },
  { id: "wild-atlantic-seaweed-baths-doolin", name: "Doolin", subtitle: "Co. Clare \xB7 53.02\xB0N", lat: 53.0173, lon: -9.4046, county: "Clare", province: "Munster", tideStation: "Galway", tideOffsetMinutes: -20, chartDatumOffset: 3.01, metEireannStation: "shannon", saunaName: "Wild Atlantic Seaweed Baths", saunaUrl: "https://wildatlanticseaweedbaths.com", country: "Ireland" },
  { id: "sauna-suaimhneas-whitestrand", name: "Whitestrand", subtitle: "Co. Clare \xB7 52.87\xB0N", lat: 52.8681, lon: -9.4274, county: "Clare", province: "Munster", tideStation: "Galway", tideOffsetMinutes: -20, chartDatumOffset: 3.01, metEireannStation: "shannon", saunaName: "Sauna Suaimhneas", saunaUrl: "https://saunasuaimhneas.com", country: "Ireland" },
  { id: "sauna-suaimhneas-lahinch-beach", name: "Lahinch Beach", subtitle: "Co. Clare \xB7 52.94\xB0N", lat: 52.93522, lon: -9.3502, county: "Clare", province: "Munster", tideStation: "Galway", tideOffsetMinutes: -20, chartDatumOffset: 3.01, metEireannStation: "shannon", saunaName: "Sauna Suaimhneas", saunaUrl: "https://saunasuaimhneas.com", country: "Ireland" },
  { id: "sauna-suaimhneas-clahane-shore", name: "Clahane Shore", subtitle: "Co. Clare \xB7 52.93\xB0N", lat: 52.9324, lon: -9.4216, county: "Clare", province: "Munster", tideStation: "Galway", tideOffsetMinutes: -20, chartDatumOffset: 3.01, metEireannStation: "shannon", saunaName: "Sauna Suaimhneas", saunaUrl: "https://saunasuaimhneas.com", country: "Ireland" },
  { id: "tide-side-sauna-glin-shannon-estuary", name: "Glin (Shannon estuary)", subtitle: "Co. Limerick \xB7 52.57\xB0N", lat: 52.5743, lon: -9.2806, county: "Limerick", province: "Munster", tideStation: "Galway", tideOffsetMinutes: -30, chartDatumOffset: 3.01, metEireannStation: "shannon", saunaName: "Tide Side Sauna", saunaUrl: "https://instagram.com/tidesidesauna", country: "Ireland" },
  { id: "brandon-bay-sauna-castlegregory", name: "Castlegregory", subtitle: "Co. Kerry \xB7 52.30\xB0N", lat: 52.3028, lon: -10.0411, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Brandon Bay Sauna", saunaUrl: "https://brandonbaysauna.com", country: "Ireland" },
  { id: "sona-sauna-ventry", name: "Ventry", subtitle: "Co. Kerry \xB7 52.13\xB0N", lat: 52.1328, lon: -10.3633, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Sona Sauna", saunaUrl: "https://www.sonasauna.ie/", country: "Ireland" },
  { id: "inch-sauna-inch-beach", name: "Inch Beach", subtitle: "Co. Kerry \xB7 52.14\xB0N", lat: 52.1394, lon: -9.9781, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Inch Sauna", saunaUrl: "https://bookwhen.com/inchsauna", country: "Ireland" },
  { id: "ballybunion-atlantic-sauna-ballybunion-beach", name: "Ballybunion Beach", subtitle: "Co. Kerry \xB7 52.51\xB0N", lat: 52.5097, lon: -9.6753, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Ballybunion Atlantic Sauna", saunaUrl: "https://flutterwbdev.azurewebsites.net/#/tenantDetails?tenantName=Ballybunion_Atlantic_Sauna", country: "Ireland" },
  { id: "rossbeigh-sauna-rossbeigh", name: "Rossbeigh", subtitle: "Co. Kerry \xB7 52.07\xB0N", lat: 52.0673, lon: -9.9758, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Rossbeigh Sauna", saunaUrl: "https://instagram.com/rossbeigh_sauna", country: "Ireland" },
  { id: "skellig-sauna-cuas-crom-beach", name: "Cuas Crom Beach", subtitle: "Co. Kerry \xB7 51.97\xB0N", lat: 51.965, lon: -10.2648, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Skellig Sauna", saunaUrl: "https://skelligsauna.ie", country: "Ireland" },
  { id: "skellig-sauna-st-finian-s-bay", name: "St. Finian's Bay", subtitle: "Co. Kerry \xB7 51.85\xB0N", lat: 51.8462, lon: -10.3365, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Skellig Sauna", saunaUrl: "https://skelligsauna.ie", country: "Ireland" },
  { id: "skellig-sauna-ballinskelligs-beach", name: "Ballinskelligs Beach", subtitle: "Co. Kerry \xB7 51.82\xB0N", lat: 51.8213, lon: -10.2729, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Skellig Sauna", saunaUrl: "https://skelligsauna.ie", country: "Ireland" },
  { id: "fire-and-ice-sauna-ballinskelligs-beach", name: "Ballinskelligs Beach", subtitle: "Co. Kerry \xB7 51.82\xB0N", lat: 51.8249, lon: -10.2708, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Fire and Ice Sauna", saunaUrl: "https://fire-and-ice-sauna.com", country: "Ireland" },
  { id: "kingdom-sauna-kerry-derrynane-beach", name: "Derrynane Beach", subtitle: "Co. Kerry \xB7 51.76\xB0N", lat: 51.76, lon: -10.1367, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Kingdom Sauna Kerry", saunaUrl: "https://kingdomsauna.ie", country: "Ireland" },
  { id: "sunset-sauna-coornagillagh-beach", name: "Coornagillagh Beach", subtitle: "Co. Kerry \xB7 51.82\xB0N", lat: 51.8247, lon: -9.74015, county: "Kerry", province: "Munster", tideStation: "Fenit", tideOffsetMinutes: 15, chartDatumOffset: 2.67, metEireannStation: "valentia", saunaName: "Sunset Sauna", saunaUrl: "https://sunsetsaunabeara.com/", country: "Ireland" },
  { id: "sunset-sauna-ballydonegan-allihies", name: "Ballydonegan", subtitle: "Co. Cork \xB7 51.63\xB0N", lat: 51.6336, lon: -10.0596, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Sunset Sauna", saunaUrl: "https://sunsetsaunabeara.com/", country: "Ireland" },
  { id: "betterdayz-sauna-warren-beach", name: "Warren Beach", subtitle: "Co. Cork \xB7 51.57\xB0N", lat: 51.5658, lon: -9.0148, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Betterdayz Sauna", saunaUrl: "https://warrensauna.as.me/", country: "Ireland" },
  { id: "the-recovery-pod-sauna-inchydoney", name: "Inchydoney", subtitle: "Co. Cork \xB7 51.60\xB0N", lat: 51.5967, lon: -8.8653, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "The Recovery Pod Sauna", saunaUrl: "https://therecoverypods.com", country: "Ireland" },
  { id: "element-wellness-dunworley-beach", name: "Dunworley Beach", subtitle: "Co. Cork \xB7 51.58\xB0N", lat: 51.5825, lon: -8.7507, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Element Wellness", saunaUrl: "https://elementwellness.ie", country: "Ireland" },
  { id: "wild-wellness-sauna-garretstown-beach", name: "Garretstown Beach", subtitle: "Co. Cork \xB7 51.64\xB0N", lat: 51.6441, lon: -8.58, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Wild Wellness Sauna", saunaUrl: "https://wildwellness.ie", country: "Ireland" },
  { id: "the-sauna-snugg-garrylucas-beach", name: "Garrylucas Beach", subtitle: "Co. Cork \xB7 51.64\xB0N", lat: 51.6397, lon: -8.5652, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "The Sauna Snugg", saunaUrl: "https://www.thesaunasnugg.com/book-now", country: "Ireland" },
  { id: "my-haven-sauna-oysterhaven", name: "Oysterhaven", subtitle: "Co. Cork \xB7 51.69\xB0N", lat: 51.6937, lon: -8.4421, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "My Haven Sauna", saunaUrl: "https://myhaven.ie", country: "Ireland" },
  { id: "swede-sauna-roberts-cove", name: "Roberts Cove", subtitle: "Co. Cork \xB7 51.74\xB0N", lat: 51.7444, lon: -8.3131, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Swede Sauna", saunaUrl: "https://instagram.com/swede_sauna", country: "Ireland" },
  { id: "my-hot-spot-sauna-redbarn-beach-youghal", name: "Redbarn Beach", subtitle: "Co. Cork \xB7 51.93\xB0N", lat: 51.9333, lon: -7.85, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "My Hot Spot Sauna", saunaUrl: "https://www.myhotspot.ie/", country: "Ireland" },
  { id: "the-hot-pod-clonea-kilmurrin-cove-dunmore-east-newtown-cove", name: "Clonea / Kilmurrin Cove / Dunmore East / Newtown Cove", subtitle: "Co. Waterford \xB7 52.08\xB0N", lat: 52.082, lon: -7.536, county: "Waterford", province: "Munster", tideStation: "Dunmore East", tideOffsetMinutes: 5, metEireannStation: "johnstown-castle", saunaName: "The Hot Pod", saunaUrl: "https://www.thehotpod.ie/book-online", country: "Ireland" },
  { id: "saltee-sauna-kilmore-quay", name: "Kilmore Quay", subtitle: "Co. Wexford \xB7 52.17\xB0N", lat: 52.174, lon: -6.587, county: "Wexford", province: "Leinster", tideStation: "Arklow", tideOffsetMinutes: 15, chartDatumOffset: 0.59, metEireannStation: "johnstown-castle", saunaName: "Saltee Sauna", saunaUrl: "https://www.salteesauna.ie/book", country: "Ireland" },
  { id: "sweathouse-baginbun-beach-fethard-on-sea", name: "Baginbun Beach", subtitle: "Co. Wexford \xB7 52.18\xB0N", lat: 52.179, lon: -6.835, county: "Wexford", province: "Leinster", tideStation: "Arklow", tideOffsetMinutes: 15, chartDatumOffset: 0.59, metEireannStation: "johnstown-castle", saunaName: "Sweathouse", saunaUrl: "https://www.sweathouse.ie/bookings.html", country: "Ireland" },
  { id: "the-sea-sauna-tower-bay-beach-portrane", name: "Tower Bay Beach", subtitle: "Co. Dublin \xB7 53.49\xB0N", lat: 53.492, lon: -6.11, county: "Dublin", province: "Leinster", tideStation: "Howth", tideOffsetMinutes: 0, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "The Sea Sauna", saunaUrl: "https://www.theseasauna.ie/bookings", country: "Ireland" },
  { id: "fad-saoil-saunas-forty-foot-sandycove", name: "Forty Foot", subtitle: "Co. Dublin \xB7 53.29\xB0N", lat: 53.289, lon: -6.113, county: "Dublin", province: "Leinster", tideStation: "Howth", tideOffsetMinutes: 0, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "Fad Saoil Saunas", saunaUrl: "https://sandycovesaunabythesea.ie/", country: "Ireland" },
  { id: "the-hot-box-sauna-dublin-forty-foot-sandycove", name: "Forty Foot", subtitle: "Co. Dublin \xB7 53.29\xB0N", lat: 53.289, lon: -6.113, county: "Dublin", province: "Leinster", tideStation: "Howth", tideOffsetMinutes: 0, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "The Hot Box Sauna (Dublin)", saunaUrl: "https://thehotboxsauna.ie", country: "Ireland" },
  { id: "helios-sauna-bray-seafront-also-dun-laoghaire-dundrum-rosslare", name: "Bray Seafront (also Dun Laoghaire", subtitle: "Co. Wicklow \xB7 53.20\xB0N", lat: 53.201, lon: -6.098, county: "Wicklow", province: "Leinster", tideStation: "Arklow", tideOffsetMinutes: -10, chartDatumOffset: 0.59, metEireannStation: "dublin-airport", saunaName: "Helios Sauna", saunaUrl: "https://heliossauna.ie/products/bray-rooftop", country: "Ireland" },
  { id: "bosca-beatha-glenmalure-valley-touring-festivals", name: "Glenmalure Valley + touring festivals", subtitle: "Co. Wicklow \xB7 52.97\xB0N", lat: 52.97, lon: -6.35, county: "Wicklow", province: "Leinster", tideStation: "Arklow", tideOffsetMinutes: -10, chartDatumOffset: 0.59, metEireannStation: "dublin-airport", saunaName: "Bosca Beatha", saunaUrl: "https://www.boscabeatha.ie/bookings", country: "Ireland" },
  { id: "sauna-sea-portstewart-strand", name: "Portstewart Strand", subtitle: "Co. Derry \xB7 Northern Ireland \xB7 55.17\xB0N", lat: 55.167, lon: -6.735, county: "Derry (NI)", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "Sauna & Sea", saunaUrl: "https://www.saunaandsea.co.uk/bookings", country: "Ireland" },
  { id: "hotbox-sea-sauna-benone-strand", name: "Benone Strand", subtitle: "Co. Derry \xB7 Northern Ireland \xB7 55.16\xB0N", lat: 55.162, lon: -6.89, county: "Derry (NI)", province: "Ulster", tideStation: "Aranmore", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "malin-head", saunaName: "HotBox Sea Sauna", saunaUrl: "https://hotboxseasauna.com", country: "Ireland" },
  { id: "hotbox-sea-sauna-groomsport-harbour", name: "Groomsport Harbour", subtitle: "Co. Down \xB7 Northern Ireland \xB7 54.68\xB0N", lat: 54.681, lon: -5.617, county: "Down (NI)", province: "Ulster", tideStation: "Howth", tideOffsetMinutes: 20, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "HotBox Sea Sauna", saunaUrl: "https://hotboxseasauna.com", country: "Ireland" },
  { id: "the-wee-sauna-portmuck-harbour-islandmagee", name: "Portmuck Harbour", subtitle: "Co. Antrim \xB7 Northern Ireland \xB7 54.84\xB0N", lat: 54.839, lon: -5.692, county: "Antrim (NI)", province: "Ulster", tideStation: "Howth", tideOffsetMinutes: 30, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "The Wee Sauna", saunaUrl: "https://facebook.com/theweesaunani", country: "Ireland" },
  { id: "scenic-sauna-ballygally-via-ballygally-castle", name: "Ballygally (via Ballygally Castle)", subtitle: "Co. Antrim \xB7 Northern Ireland \xB7 54.90\xB0N", lat: 54.897, lon: -5.855, county: "Antrim (NI)", province: "Ulster", tideStation: "Howth", tideOffsetMinutes: 30, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "Scenic Sauna", saunaUrl: "https://www.facebook.com/p/A-Scenic-Sauna-61554134446296/", country: "Ireland" },
  { id: "happy-place-fountainstown", name: "Fountainstown", subtitle: "Co. Cork \xB7 51.77\xB0N", lat: 51.77, lon: -8.286, county: "Cork", province: "Munster", tideStation: "Cobh", tideOffsetMinutes: 15, chartDatumOffset: 2.2, metEireannStation: "roches-point", saunaName: "Happy Place", saunaUrl: "https://happyplacesaunas.ie/", country: "Ireland" },
  { id: "the-sauna-society-multiple", name: "Multiple", subtitle: "Co. Dublin \xB7 53.35\xB0N", lat: 53.349, lon: -6.26, county: "Dublin", province: "Leinster", tideStation: "Howth", tideOffsetMinutes: 0, chartDatumOffset: 2.68, metEireannStation: "dublin-airport", saunaName: "The Sauna Society", saunaUrl: "https://www.thesaunasociety.ie/bookings", country: "Ireland" },
  { id: "seacoast-beaumaris", name: "Beaumaris", subtitle: "Anglesey (North Wales) \xB7 Wales \xB7 53.26\xB0N", lat: 53.264, lon: -4.09, county: "Anglesey (North Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Seacoast", saunaUrl: "https://seacoastsauna.co.uk/book", country: "Wales" },
  { id: "sawna-bach-porth-tyn-tywyn", name: "Porth Tyn Tywyn", subtitle: "Anglesey (North Wales) \xB7 Wales \xB7 53.22\xB0N", lat: 53.216, lon: -4.436, county: "Anglesey (North Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sawna Bach", saunaUrl: "https://saunawales.co.uk", country: "Wales" },
  { id: "sawna-bach-llyn-padarn-llanberis", name: "Llyn Padarn", subtitle: "Gwynedd (North Wales) \xB7 Wales \xB7 53.12\xB0N", lat: 53.123, lon: -4.123, county: "Gwynedd (North Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sawna Bach", saunaUrl: "https://saunawales.co.uk", country: "Wales" },
  { id: "casgen-porth-eirias-colwyn-bay", name: "Porth Eirias", subtitle: "Conwy (North Wales) \xB7 Wales \xB7 53.30\xB0N", lat: 53.296, lon: -3.717, county: "Conwy (North Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Casgen", saunaUrl: "https://instagram.com/casgensawna", country: "Wales" },
  { id: "sauna-mor-aberdaron-llyn-peninsula", name: "Aberdaron", subtitle: "Gwynedd (North Wales) \xB7 Wales \xB7 52.80\xB0N", lat: 52.805, lon: -4.711, county: "Gwynedd (North Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sauna Mor", saunaUrl: "https://app.acuityscheduling.com/schedule.php?owner=34400399", country: "Wales" },
  { id: "aberpoeth-aberystwyth-promenade", name: "Aberystwyth Promenade", subtitle: "Ceredigion (West Wales) \xB7 Wales \xB7 52.42\xB0N", lat: 52.416, lon: -4.086, county: "Ceredigion (West Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Aberpoeth", saunaUrl: "https://www.aberpoeth.co.uk/appointments", country: "Wales" },
  { id: "sawna-llosgi-llangrannog-beach", name: "Llangrannog Beach", subtitle: "Ceredigion (West Wales) \xB7 Wales \xB7 52.16\xB0N", lat: 52.156, lon: -4.466, county: "Ceredigion (West Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sawna Llosgi", saunaUrl: "https://sawnallosgi.as.me/schedule/c819d9a6", country: "Wales" },
  { id: "wildwater-sauna-roving-newgale-whitesands", name: "Roving - Newgale / Whitesands", subtitle: "Pembrokeshire (West Wales) \xB7 Wales \xB7 51.86\xB0N", lat: 51.858, lon: -5.108, county: "Pembrokeshire (West Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wildwater Sauna", saunaUrl: "https://www.wildwatersauna.com/book-now/", country: "Wales" },
  { id: "logi-saunas-pembrokeshire-mobile", name: "Pembrokeshire (mobile)", subtitle: "Pembrokeshire (West Wales) \xB7 Wales \xB7 51.70\xB0N", lat: 51.7, lon: -5.05, county: "Pembrokeshire (West Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Logi Saunas", saunaUrl: "https://logisaunas.co.uk", country: "Wales" },
  { id: "hikitalo-porthcawl", name: "Porthcawl", subtitle: "Bridgend (South Wales) \xB7 Wales \xB7 51.48\xB0N", lat: 51.479, lon: -3.705, county: "Bridgend (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Hikitalo", saunaUrl: "https://hikitalo.com/pages/location", country: "Wales" },
  { id: "ty-sawna-oxwich-bay", name: "Oxwich Bay", subtitle: "Swansea/Gower (South Wales) \xB7 Wales \xB7 51.56\xB0N", lat: 51.556, lon: -4.167, county: "Swansea/Gower (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Ty Sawna", saunaUrl: "https://tysawna.co.uk", country: "Wales" },
  { id: "mor-a-sawna-jacksons-bay-barry", name: "Jacksons Bay", subtitle: "Vale of Glamorgan (South Wales) \xB7 Wales \xB7 51.39\xB0N", lat: 51.392, lon: -3.266, county: "Vale of Glamorgan (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Mor a Sawna", saunaUrl: "https://www.xn--mrasawna-43a.com/book-now", country: "Wales" },
  { id: "sauna-hut-wales-langland-bay", name: "Langland Bay", subtitle: "Swansea/Gower (South Wales) \xB7 Wales \xB7 51.57\xB0N", lat: 51.568, lon: -4.003, county: "Swansea/Gower (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sauna Hut Wales", saunaUrl: "https://saunahutwales.co.uk", country: "Wales" },
  { id: "sauna-hut-wales-parkmill-river", name: "Parkmill (river)", subtitle: "Swansea/Gower (South Wales) \xB7 Wales \xB7 51.58\xB0N", lat: 51.584, lon: -4.108, county: "Swansea/Gower (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sauna Hut Wales", saunaUrl: "https://saunahutwales.co.uk", country: "Wales" },
  { id: "sea-and-steam-saundersfoot-beach", name: "Saundersfoot Beach", subtitle: "Pembrokeshire (South Wales) \xB7 Wales \xB7 51.71\xB0N", lat: 51.711, lon: -4.697, county: "Pembrokeshire (South Wales)", province: "Wales", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sea and Steam", saunaUrl: "https://seaandsteam.co.uk/book/", country: "Wales" },
  { id: "saunas-by-the-sea-polzeath-harlyn-bay", name: "Polzeath / Harlyn Bay", subtitle: "Cornwall (South West) \xB7 England \xB7 50.57\xB0N", lat: 50.57, lon: -4.917, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Saunas by the Sea", saunaUrl: "https://www.saunasbythesea.co.uk/book-now/", country: "England" },
  { id: "olla-hiki-fistral-watergate-bay-newquay-harbour", name: "Great Western Beach, Newquay", subtitle: "Cornwall (South West) \xB7 England \xB7 50.42\xB0N", lat: 50.418, lon: -5.093, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Olla Hiki", saunaUrl: "https://www.ollahikisauna.co.uk/booking", country: "England" },
  { id: "rising-embers-newlyn-green-penzance", name: "Newlyn Green", subtitle: "Cornwall (South West) \xB7 England \xB7 50.11\xB0N", lat: 50.108, lon: -5.544, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Rising Embers", saunaUrl: "https://risingembers.com/", country: "England" },
  { id: "kiln-sauna-gyllyngvase-beach-falmouth-flushing-mylor", name: "Gyllyngvase Beach Falmouth / Flushing / Mylor", subtitle: "Cornwall (South West) \xB7 England \xB7 50.14\xB0N", lat: 50.143, lon: -5.068, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Kiln Sauna", saunaUrl: "https://www.kilnsauna.com/gylly-beach-falmouth", country: "England" },
  { id: "ocean-soul-sauna-widemouth-beach-bude", name: "Crooklets Beach, Bude", subtitle: "Cornwall (South West) \xB7 England \xB7 50.79\xB0N", lat: 50.786, lon: -4.556, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Ocean Soul Sauna", saunaUrl: "https://www.oceansoulsauna.co.uk/book", country: "England" },
  { id: "escape-sea-swim-and-sauna-maenporth-beach-falmouth", name: "Maenporth Beach", subtitle: "Cornwall (South West) \xB7 England \xB7 50.13\xB0N", lat: 50.133, lon: -5.09, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Escape Sea Swim and Sauna", saunaUrl: "https://maenporthsauna.com/", country: "England" },
  { id: "seaside-sauna-haus-seatown-beach", name: "Seatown Beach", subtitle: "Dorset (South West) \xB7 England \xB7 50.71\xB0N", lat: 50.711, lon: -2.819, county: "Dorset (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Seaside Sauna Haus", saunaUrl: "https://www.seasidesaunahaus.co.uk/booking-options", country: "England" },
  { id: "devon-community-sauna-teignmouth", name: "Teignmouth", subtitle: "Devon (South West) \xB7 England \xB7 50.55\xB0N", lat: 50.547, lon: -3.496, county: "Devon (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Devon Community Sauna", saunaUrl: "https://devoncommunitysauna.co.uk", country: "England" },
  { id: "devon-community-sauna-exmouth", name: "Exmouth", subtitle: "Devon (South West) \xB7 England \xB7 50.62\xB0N", lat: 50.616, lon: -3.413, county: "Devon (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Devon Community Sauna", saunaUrl: "https://devoncommunitysauna.co.uk", country: "England" },
  { id: "lynmouth-sea-sauna-dip-blacklands-beach-lynmouth", name: "Blacklands Beach", subtitle: "Devon (South West) \xB7 England \xB7 51.23\xB0N", lat: 51.233, lon: -3.833, county: "Devon (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Lynmouth Sea Sauna & Dip", saunaUrl: "https://www.eventbrite.co.uk/o/lynseals-lynmouth-sailing-club", country: "England" },
  { id: "beach-box-spa-brighton-beach", name: "Brighton Beach", subtitle: "Sussex (South coast) \xB7 England \xB7 50.82\xB0N", lat: 50.819, lon: -0.128, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Beach Box Spa", saunaUrl: "https://beachboxspa.co.uk/book-now/", country: "England" },
  { id: "luna-hut-sauna-sea-lanes-brighton", name: "Sea Lanes", subtitle: "Sussex (South coast) \xB7 England \xB7 50.82\xB0N", lat: 50.817, lon: -0.118, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Luna Hut Sauna", saunaUrl: "https://www.lunahutsauna.co.uk/brightonsealanes", country: "England" },
  { id: "the-nomadic-sauna-kingston-beach-shoreham", name: "Kingston Beach", subtitle: "Sussex (South coast) \xB7 England \xB7 50.83\xB0N", lat: 50.829, lon: -0.248, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "The Nomadic Sauna", saunaUrl: "https://www.thenomadicsauna.co.uk/book", country: "England" },
  { id: "the-nomadic-sauna-seaford", name: "Seaford", subtitle: "Sussex (South coast) \xB7 England \xB7 50.77\xB0N", lat: 50.77, lon: 0.101, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "The Nomadic Sauna", saunaUrl: "https://www.thenomadicsauna.co.uk/book", country: "England" },
  { id: "widewater-sauna-widewater-lagoon-lancing", name: "Widewater Lagoon", subtitle: "Sussex (South coast) \xB7 England \xB7 50.83\xB0N", lat: 50.827, lon: -0.326, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Widewater Sauna", saunaUrl: "https://widewatersauna.as.me/schedule.php", country: "England" },
  { id: "fire-salt-sea-worthing-beach", name: "Worthing Beach", subtitle: "Sussex (South coast) \xB7 England \xB7 50.81\xB0N", lat: 50.808, lon: -0.372, county: "Sussex (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Fire, Salt & Sea", saunaUrl: "https://firesaltsea.co.uk", country: "England" },
  { id: "the-little-sauna-company-sandgate", name: "Hythe (Princes Parade)", subtitle: "Kent (South coast) \xB7 England \xB7 51.07\xB0N", lat: 51.073, lon: 1.148, county: "Kent (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "The Little Sauna Company", saunaUrl: "https://www.thelittlesauna.com/", country: "England" },
  { id: "folkestone-sea-sauna-folkestone", name: "Folkestone", subtitle: "Kent (South coast) \xB7 England \xB7 51.08\xB0N", lat: 51.079, lon: 1.186, county: "Kent (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Folkestone Sea Sauna", saunaUrl: "https://www.folkestoneseasauna.com/", country: "England" },
  { id: "haeckels-walpole-bay-margate", name: "Walpole Bay", subtitle: "Kent (South coast) \xB7 England \xB7 51.39\xB0N", lat: 51.387, lon: 1.401, county: "Kent (South coast)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Haeckels", saunaUrl: "https://haeckels.co.uk", country: "England" },
  { id: "sauna-box-sea-palling-sheringham-dunwich-festivals", name: "Sea Palling / Sheringham / Dunwich + festivals", subtitle: "Norfolk (East Anglia) \xB7 England \xB7 52.79\xB0N", lat: 52.79, lon: 1.597, county: "Norfolk (East Anglia)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sauna Box", saunaUrl: "https://saunabox.co.uk/book", country: "England" },
  { id: "whitby-wellbeing-saltburn-runswick-bay-sandsend-whitby-scarborough", name: "Saltburn / Runswick Bay / Sandsend / Whitby / Scarborough", subtitle: "Yorkshire (North East) \xB7 England \xB7 54.58\xB0N", lat: 54.584, lon: -0.971, county: "Yorkshire (North East)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Whitby Wellbeing", saunaUrl: "https://whitbywellbeing.com", country: "England" },
  { id: "dip-dales-co-draughton-heights-skipton", name: "Draughton Heights", subtitle: "Yorkshire \xB7 England \xB7 53.96\xB0N", lat: 53.956, lon: -1.956, county: "Yorkshire", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Dip & Dales Co", saunaUrl: "https://loylyandjaa.co.uk/sauna-booking", country: "England" },
  { id: "rx4-lakes-st-bees-beach-lake-district-mobile", name: "St Bees Beach + Lake District (mobile)", subtitle: "Cumbria (North West) \xB7 England \xB7 54.49\xB0N", lat: 54.493, lon: -3.616, county: "Cumbria (North West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "RX4 Lakes", saunaUrl: "https://www.rx4lakes.co.uk/our-events", country: "England" },
  { id: "la-al-sauna-coniston-water-fell-foot-windermere", name: "Bank Ground Farm, Coniston Water", subtitle: "Cumbria (North West) \xB7 England \xB7 54.37\xB0N", lat: 54.368, lon: -3.068, county: "Cumbria (North West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "La'al Sauna", saunaUrl: "https://www.laalsauna.co.uk/product/book-laal-sauna/", country: "England" },
  { id: "fellside-sauna-ullswater-waterside-house-campsite", name: "Ullswater + Waterside House Campsite", subtitle: "Cumbria (North West) \xB7 England \xB7 54.58\xB0N", lat: 54.58, lon: -2.9, county: "Cumbria (North West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Fellside Sauna", saunaUrl: "https://fellsidesauna.as.me/", country: "England" },
  { id: "fahrenhut-pooley-bridge-ullswater", name: "Park Foot, Howtown (nr Pooley Bridge)", subtitle: "Cumbria (North West) \xB7 England \xB7 54.61\xB0N", lat: 54.613, lon: -2.82, county: "Cumbria (North West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Fahrenhut", saunaUrl: "https://fahrenhutsauna.co.uk/book-fahrenhut/", country: "England" },
  { id: "crooklets-beach-squircle-sauna-crooklets-beach-bude", name: "Crooklets Beach", subtitle: "Cornwall (South West) \xB7 England \xB7 50.84\xB0N", lat: 50.836, lon: -4.556, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Crooklets Beach 'squircle' sauna", country: "England" },
  { id: "saunassa-newquay", name: "Newquay", subtitle: "Cornwall (South West) \xB7 England \xB7 50.41\xB0N", lat: 50.415, lon: -5.081, county: "Cornwall (South West)", province: "England", tideStation: "", tideOffsetMinutes: 0, saunaName: "Saunassa", saunaUrl: "https://saunassa.co.uk/book/", country: "England" },
  { id: "soul-water-sauna-portobello-beach-promenade", name: "Portobello Beach Promenade", subtitle: "Edinburgh \xB7 Scotland \xB7 55.95\xB0N", lat: 55.955, lon: -3.113, county: "Edinburgh", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Soul Water Sauna", saunaUrl: "https://soulwatersauna.com/portobello", country: "Scotland" },
  { id: "spear-sauna-lost-shore-surf-resort-ratho", name: "Lost Shore Surf Resort, Ratho", subtitle: "Edinburgh \xB7 Scotland \xB7 55.90\xB0N", lat: 55.902, lon: -3.376, county: "Edinburgh", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Spear Sauna", saunaUrl: "https://www.spearsauna.co.uk", country: "Scotland" },
  { id: "drift-north-berwick-dunes", name: "North Berwick (dunes)", subtitle: "East Lothian \xB7 Scotland \xB7 56.05\xB0N", lat: 56.048, lon: -2.735, county: "East Lothian", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Drift", saunaUrl: "https://escapesauna.co.uk/book-escape-to-the-bay", country: "Scotland" },
  { id: "hot-bothy-archerfield-walled-garden-dirleton", name: "Archerfield Walled Garden, Dirleton", subtitle: "East Lothian \xB7 Scotland \xB7 56.06\xB0N", lat: 56.056, lon: -2.84, county: "East Lothian", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Hot & Bothy", saunaUrl: "https://www.hotandbothysauna.co.uk/bookings", country: "Scotland" },
  { id: "foxlake-adventures-sauna-dunbar", name: "Dunbar", subtitle: "East Lothian \xB7 Scotland \xB7 56.00\xB0N", lat: 55.999, lon: -2.47, county: "East Lothian", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Foxlake Adventures Sauna", saunaUrl: "https://www.foxlake.co.uk/sauna", country: "Scotland" },
  { id: "elie-seaside-sauna-elie-harbour-dunes", name: "Elie Harbour (dunes)", subtitle: "Fife \xB7 Scotland \xB7 56.19\xB0N", lat: 56.188, lon: -2.82, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Elie Seaside Sauna", saunaUrl: "https://www.elieseasidesauna.com/booking/", country: "Scotland" },
  { id: "wild-scottish-sauna-shell-bay-elie", name: "Shell Bay, Elie", subtitle: "Fife \xB7 Scotland \xB7 56.20\xB0N", lat: 56.196, lon: -2.835, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Scottish Sauna", saunaUrl: "https://wildscottishsauna.com", country: "Scotland" },
  { id: "wild-scottish-sauna-kingsbarns-beach", name: "Kingsbarns Beach", subtitle: "Fife \xB7 Scotland \xB7 56.30\xB0N", lat: 56.303, lon: -2.654, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Scottish Sauna", saunaUrl: "https://wildscottishsauna.com", country: "Scotland" },
  { id: "wild-scottish-sauna-west-sands-st-andrews", name: "West Sands, St Andrews", subtitle: "Fife \xB7 Scotland \xB7 56.34\xB0N", lat: 56.345, lon: -2.806, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Scottish Sauna", saunaUrl: "https://wildscottishsauna.com", country: "Scotland" },
  { id: "wild-scottish-sauna-forbes-of-kingennie-nr-dundee", name: "Forbes of Kingennie, nr Dundee", subtitle: "Angus \xB7 Scotland \xB7 56.49\xB0N", lat: 56.49, lon: -2.86, county: "Angus", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Scottish Sauna", saunaUrl: "https://wildscottishsauna.com", country: "Scotland" },
  { id: "cellardyke-seaside-sauna-cellardyke", name: "Cellardyke", subtitle: "Fife \xB7 Scotland \xB7 56.22\xB0N", lat: 56.221, lon: -2.692, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Cellardyke Seaside Sauna", saunaUrl: "https://cellardykeseasidesauna.com", country: "Scotland" },
  { id: "castaway-sauna-lower-largo-largo-bay", name: "Lower Largo, Largo Bay", subtitle: "Fife \xB7 Scotland \xB7 56.21\xB0N", lat: 56.213, lon: -2.925, county: "Fife", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Castaway Sauna", saunaUrl: "https://largocastawaysauna.co.uk", country: "Scotland" },
  { id: "watershed-sauna-findhorn-east-beach", name: "Findhorn East Beach", subtitle: "Moray \xB7 Scotland \xB7 57.66\xB0N", lat: 57.66, lon: -3.615, county: "Moray", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Watershed Sauna", saunaUrl: "https://watershedsauna.com/book", country: "Scotland" },
  { id: "barbossauna-aberdeen-esplanade-footdee", name: "Aberdeen Esplanade / Footdee", subtitle: "Aberdeen \xB7 Scotland \xB7 57.15\xB0N", lat: 57.145, lon: -2.078, county: "Aberdeen", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Barbossauna", saunaUrl: "https://www.barbossauna.co.uk", country: "Scotland" },
  { id: "cromarty-community-sauna-cromarty-ferry-slipway-black-isle", name: "Cromarty ferry slipway, Black Isle", subtitle: "Highland \xB7 Scotland \xB7 57.68\xB0N", lat: 57.681, lon: -4.038, county: "Highland", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Cromarty Community Sauna", saunaUrl: "https://cromartysauna.com", country: "Scotland" },
  { id: "wild-bathing-tralee-bay-coastal-park-nr-oban-2-locations", name: "Tralee Bay Coastal Park, nr Oban (2 locations)", subtitle: "Argyll & Bute \xB7 Scotland \xB7 56.48\xB0N", lat: 56.485, lon: -5.355, county: "Argyll & Bute", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Bathing", saunaUrl: "https://wildbathing.as.me/schedule/0e3ace06", country: "Scotland" },
  { id: "staffin-sea-sauna-staffin-harbour", name: "Staffin Harbour", subtitle: "Isle of Skye \xB7 Scotland \xB7 57.62\xB0N", lat: 57.623, lon: -6.21, county: "Isle of Skye", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Staffin Sea Sauna", saunaUrl: "https://www.staffinseasauna.com/appointments", country: "Scotland" },
  { id: "wild-sauna-arran-green-goddess-blackwaterfoot-beach", name: "Blackwaterfoot Beach", subtitle: "Isle of Arran \xB7 Scotland \xB7 55.50\xB0N", lat: 55.496, lon: -5.33, county: "Isle of Arran", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Sauna Arran (Green Goddess)", saunaUrl: "https://www.wildsauna.scot", country: "Scotland" },
  { id: "stonesthrow-sauna-arran-beach-fixed", name: "Whiting Bay, Arran", subtitle: "Isle of Arran \xB7 Scotland \xB7 55.48\xB0N", lat: 55.48, lon: -5.13, county: "Isle of Arran", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Stonesthrow Sauna", saunaUrl: "https://www.stonesthrowsauna.co.uk/book", country: "Scotland" },
  { id: "sauna-wanna-stromness-pier-harbour", name: "Stromness pier/harbour", subtitle: "Orkney \xB7 Scotland \xB7 58.97\xB0N", lat: 58.965, lon: -3.298, county: "Orkney", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Sauna Wanna", saunaUrl: "https://instagram.com/saunawanna", country: "Scotland" },
  { id: "haar-sauna-st-ninian-s-beach-tombolo", name: "St Ninian's Beach (tombolo)", subtitle: "Shetland \xB7 Scotland \xB7 59.97\xB0N", lat: 59.97, lon: -1.345, county: "Shetland", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Haar Sauna", saunaUrl: "https://www.haarsauna.com/book-sauna", country: "Scotland" },
  { id: "saltbox-sauna-stornoway", name: "Reef Beach / Loch Barvas, Lewis", subtitle: "Isle of Lewis \xB7 Scotland \xB7 58.21\xB0N", lat: 58.209, lon: -6.386, county: "Isle of Lewis", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Saltbox Sauna", saunaUrl: "https://saltboxsauna.co.uk/book/", country: "Scotland" },
  { id: "wild-dook-sauna-mossyard-beach-touring-d-g-borders", name: "Mossyard Beach + touring D&G/Borders", subtitle: "Dumfries & Galloway \xB7 Scotland \xB7 54.84\xB0N", lat: 54.84, lon: -4.29, county: "Dumfries & Galloway", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Wild Dook Sauna", saunaUrl: "https://www.wilddooksauna.com/book", country: "Scotland" },
  { id: "hotbox-sauna-taymouth-taymouth-marina-loch-tay-floating", name: "Taymouth Marina, Loch Tay (floating)", subtitle: "Perth & Kinross \xB7 Scotland \xB7 56.59\xB0N", lat: 56.595, lon: -4.07, county: "Perth & Kinross", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "HotBox Sauna (Taymouth)", saunaUrl: "https://www.taymouthmarina.com/hotbox-spa-booking-page/", country: "Scotland" },
  { id: "braan-sauna-the-taybank-dunkeld-riverside", name: "The Taybank, Dunkeld (riverside)", subtitle: "Perth & Kinross \xB7 Scotland \xB7 56.56\xB0N", lat: 56.565, lon: -3.59, county: "Perth & Kinross", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Braan Sauna", saunaUrl: "https://www.thetaybank.co.uk/sauna", country: "Scotland" },
  { id: "cullen-beach-sauna-cullen-beach", name: "Cullen Beach", subtitle: "Moray \xB7 Scotland \xB7 57.69\xB0N", lat: 57.685, lon: -2.82, county: "Moray", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Cullen Beach Sauna", saunaUrl: "https://www.saunaatthekings.co.uk", country: "Scotland" },
  { id: "hopeman-dunes-sauna-hopeman-dunes-moray-firth", name: "Hopeman dunes, Moray Firth", subtitle: "Moray \xB7 Scotland \xB7 57.71\xB0N", lat: 57.706, lon: -3.44, county: "Moray", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Hopeman Dunes Sauna", saunaUrl: "https://fyrhussauna.co.uk/booking/", country: "Scotland" },
  { id: "lunderston-bay-sauna-lunderston-bay-inverkip", name: "Lunderston Bay, Inverkip", subtitle: "Inverclyde \xB7 Scotland \xB7 55.92\xB0N", lat: 55.918, lon: -4.88, county: "Inverclyde", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Lunderston Bay Sauna", saunaUrl: "https://bookwhen.com/wanderingwellness", country: "Scotland" },
  { id: "loch-long-sauna-arrochar-loch-long-arrochar", name: "Loch Long, Arrochar", subtitle: "Argyll & Bute \xB7 Scotland \xB7 56.20\xB0N", lat: 56.205, lon: -4.74, county: "Argyll & Bute", province: "Scotland", tideStation: "", tideOffsetMinutes: 0, saunaName: "Loch Long Sauna (Arrochar)", saunaUrl: "https://www.eir-sauna.com/book-online", country: "Scotland" }
];
var DEFAULT_LOCATION = LOCATIONS[0];
var locationsById = new Map(
  LOCATIONS.map((l) => [l.id, l])
);

// src/lib/mcp/tools/list-saunas.ts
var list_saunas_default = defineTool({
  name: "list_saunas",
  title: "List saunas",
  description: "List coastal saunas tracked by Saunas in Ireland. Optionally filter by country (Ireland, Wales, England, Scotland) or county. Returns id, name, county, country, coordinates, and booking URL.",
  inputSchema: {
    country: z.string().optional().describe("Filter by country name, e.g. Ireland."),
    county: z.string().optional().describe("Filter by county, e.g. Kerry."),
    limit: z.number().int().min(1).max(200).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ country, county, limit }) => {
    const cap = limit ?? 50;
    const rows = LOCATIONS.filter((l) => {
      if (country && (l.country ?? "").toLowerCase() !== country.toLowerCase()) return false;
      if (county && l.county.toLowerCase() !== county.toLowerCase()) return false;
      return true;
    }).slice(0, cap).map((l) => ({
      id: l.id,
      sauna_name: l.saunaName ?? null,
      location: l.name,
      county: l.county,
      country: l.country ?? null,
      lat: l.lat,
      lon: l.lon,
      booking_url: l.saunaUrl ?? null
    }));
    return {
      content: [{ type: "text", text: `${rows.length} sauna(s) found.` }],
      structuredContent: { count: rows.length, saunas: rows }
    };
  }
});

// src/lib/mcp/tools/get-sauna.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_sauna_default = defineTool2({
  name: "get_sauna",
  title: "Get sauna",
  description: "Get full details for a single sauna by its slug id (e.g. 'cromane'). Includes coordinates, tide station, and booking URL.",
  inputSchema: {
    id: z2.string().min(1).describe("The sauna slug id, e.g. 'cromane'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const sauna = LOCATIONS.find((l) => l.id === id);
    if (!sauna) {
      return {
        content: [{ type: "text", text: `No sauna found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `${sauna.saunaName ?? sauna.name} \u2014 ${sauna.county}` }],
      structuredContent: { sauna }
    };
  }
});

// src/lib/mcp/tools/find-nearest-sauna.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function distanceKm(lat1, lon1, lat2, lon2) {
  const R = 6371;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
var find_nearest_sauna_default = defineTool3({
  name: "find_nearest_sauna",
  title: "Find nearest sauna",
  description: "Given a latitude and longitude, return the nearest coastal saunas ordered by distance in kilometres.",
  inputSchema: {
    lat: z3.number().describe("Latitude in decimal degrees."),
    lon: z3.number().describe("Longitude in decimal degrees."),
    limit: z3.number().int().min(1).max(20).optional().describe("Number of results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat, lon, limit }) => {
    const cap = limit ?? 5;
    const ranked = LOCATIONS.map((l) => ({
      id: l.id,
      sauna_name: l.saunaName ?? null,
      location: l.name,
      county: l.county,
      country: l.country ?? null,
      lat: l.lat,
      lon: l.lon,
      booking_url: l.saunaUrl ?? null,
      distance_km: Math.round(distanceKm(lat, lon, l.lat, l.lon) * 10) / 10
    })).sort((a, b) => a.distance_km - b.distance_km).slice(0, cap);
    return {
      content: [
        {
          type: "text",
          text: `Nearest sauna: ${ranked[0]?.sauna_name ?? ranked[0]?.location} (${ranked[0]?.distance_km} km).`
        }
      ],
      structuredContent: { results: ranked }
    };
  }
});

// src/lib/mcp/tools/get-home-sauna.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_home_sauna_default = defineTool4({
  name: "get_home_sauna",
  title: "Get my home sauna",
  description: "Get the signed-in user's chosen home sauna, if set. Returns the sauna slug and details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("home_sauna_slug").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const slug = data?.home_sauna_slug ?? null;
    if (!slug) {
      return {
        content: [{ type: "text", text: "No home sauna set." }],
        structuredContent: { home_sauna_slug: null, sauna: null }
      };
    }
    const sauna = LOCATIONS.find((l) => l.id === slug) ?? null;
    return {
      content: [
        { type: "text", text: `Home sauna: ${sauna?.saunaName ?? sauna?.name ?? slug}.` }
      ],
      structuredContent: { home_sauna_slug: slug, sauna }
    };
  }
});

// src/lib/mcp/tools/set-home-sauna.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_home_sauna_default = defineTool5({
  name: "set_home_sauna",
  title: "Set my home sauna",
  description: "Set the signed-in user's home sauna to the given slug id. Pass null or empty string to clear.",
  inputSchema: {
    id: z4.string().describe("Sauna slug id (e.g. 'cromane'). Pass an empty string to clear.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const slug = id.trim() || null;
    if (slug && !LOCATIONS.some((l) => l.id === slug)) {
      return {
        content: [{ type: "text", text: `Unknown sauna id '${slug}'.` }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { error } = await supabase.from("profiles").update({ home_sauna_slug: slug }).eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: slug ? `Home sauna set to '${slug}'.` : "Home sauna cleared." }
      ],
      structuredContent: { home_sauna_slug: slug }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zvzgjfhbkicoswjvnwoi";
var mcp_default = defineMcp({
  name: "saunas-in-ireland-mcp",
  title: "Saunas in Ireland",
  version: "0.1.0",
  instructions: "Tools for the Saunas in Ireland app. Use `list_saunas` and `find_nearest_sauna` to discover coastal saunas across Ireland, Wales, England, and Scotland. Use `get_home_sauna` and `set_home_sauna` to read or update the signed-in user's chosen home sauna.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_saunas_default,
    get_sauna_default,
    find_nearest_sauna_default,
    get_home_sauna_default,
    set_home_sauna_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
