// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-saunas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { LOCATIONS } from "npm:@/features/location/data/locations";
var list_saunas_default = defineTool({
  name: "list_saunas",
  title: "List saunas",
  description: "List coastal saunas tracked by Saunas in Ireland. Optionally filter by country (Ireland, Wales, England, Scotland) or county. Returns id, name, county, country, coordinates, and booking URL.",
  inputSchema: {
    country: z.string().optional().describe("Filter by country name, e.g. Ireland."),
    county: z.string().optional().describe("Filter by county, e.g. Kerry."),
    limit: z.number().int().min(1).max(200).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ country, county, limit }) => {
    const cap = limit ?? 50;
    const rows = LOCATIONS.filter((l) => {
      if (country && (l.country ?? "").toLowerCase() !== country.toLowerCase()) return false;
      if (county && l.county.toLowerCase() !== county.toLowerCase()) return false;
      return true;
    }).slice(0, cap).map((l) => ({
      id: l.id,
      sauna_name: l.saunaName ?? null,
      location: l.name,
      county: l.county,
      country: l.country ?? null,
      lat: l.lat,
      lon: l.lon,
      booking_url: l.saunaUrl ?? null
    }));
    return {
      content: [{ type: "text", text: `${rows.length} sauna(s) found.` }],
      structuredContent: { count: rows.length, saunas: rows }
    };
  }
});

// src/lib/mcp/tools/get-sauna.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { LOCATIONS as LOCATIONS2 } from "npm:@/features/location/data/locations";
var get_sauna_default = defineTool2({
  name: "get_sauna",
  title: "Get sauna",
  description: "Get full details for a single sauna by its slug id (e.g. 'cromane'). Includes coordinates, tide station, and booking URL.",
  inputSchema: {
    id: z2.string().min(1).describe("The sauna slug id, e.g. 'cromane'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const sauna = LOCATIONS2.find((l) => l.id === id);
    if (!sauna) {
      return {
        content: [{ type: "text", text: `No sauna found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `${sauna.saunaName ?? sauna.name} \u2014 ${sauna.county}` }],
      structuredContent: { sauna }
    };
  }
});

// src/lib/mcp/tools/find-nearest-sauna.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { LOCATIONS as LOCATIONS3 } from "npm:@/features/location/data/locations";
function distanceKm(lat1, lon1, lat2, lon2) {
  const R = 6371;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
var find_nearest_sauna_default = defineTool3({
  name: "find_nearest_sauna",
  title: "Find nearest sauna",
  description: "Given a latitude and longitude, return the nearest coastal saunas ordered by distance in kilometres.",
  inputSchema: {
    lat: z3.number().describe("Latitude in decimal degrees."),
    lon: z3.number().describe("Longitude in decimal degrees."),
    limit: z3.number().int().min(1).max(20).optional().describe("Number of results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat, lon, limit }) => {
    const cap = limit ?? 5;
    const ranked = LOCATIONS3.map((l) => ({
      id: l.id,
      sauna_name: l.saunaName ?? null,
      location: l.name,
      county: l.county,
      country: l.country ?? null,
      lat: l.lat,
      lon: l.lon,
      booking_url: l.saunaUrl ?? null,
      distance_km: Math.round(distanceKm(lat, lon, l.lat, l.lon) * 10) / 10
    })).sort((a, b) => a.distance_km - b.distance_km).slice(0, cap);
    return {
      content: [
        {
          type: "text",
          text: `Nearest sauna: ${ranked[0]?.sauna_name ?? ranked[0]?.location} (${ranked[0]?.distance_km} km).`
        }
      ],
      structuredContent: { results: ranked }
    };
  }
});

// src/lib/mcp/tools/get-home-sauna.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { LOCATIONS as LOCATIONS4 } from "npm:@/features/location/data/locations";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_home_sauna_default = defineTool4({
  name: "get_home_sauna",
  title: "Get my home sauna",
  description: "Get the signed-in user's chosen home sauna, if set. Returns the sauna slug and details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("home_sauna_slug").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const slug = data?.home_sauna_slug ?? null;
    if (!slug) {
      return {
        content: [{ type: "text", text: "No home sauna set." }],
        structuredContent: { home_sauna_slug: null, sauna: null }
      };
    }
    const sauna = LOCATIONS4.find((l) => l.id === slug) ?? null;
    return {
      content: [
        { type: "text", text: `Home sauna: ${sauna?.saunaName ?? sauna?.name ?? slug}.` }
      ],
      structuredContent: { home_sauna_slug: slug, sauna }
    };
  }
});

// src/lib/mcp/tools/set-home-sauna.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { LOCATIONS as LOCATIONS5 } from "npm:@/features/location/data/locations";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_home_sauna_default = defineTool5({
  name: "set_home_sauna",
  title: "Set my home sauna",
  description: "Set the signed-in user's home sauna to the given slug id. Pass null or empty string to clear.",
  inputSchema: {
    id: z4.string().describe("Sauna slug id (e.g. 'cromane'). Pass an empty string to clear.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const slug = id.trim() || null;
    if (slug && !LOCATIONS5.some((l) => l.id === slug)) {
      return {
        content: [{ type: "text", text: `Unknown sauna id '${slug}'.` }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { error } = await supabase.from("profiles").update({ home_sauna_slug: slug }).eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: slug ? `Home sauna set to '${slug}'.` : "Home sauna cleared." }
      ],
      structuredContent: { home_sauna_slug: slug }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zvzgjfhbkicoswjvnwoi";
var mcp_default = defineMcp({
  name: "saunas-in-ireland-mcp",
  title: "Saunas in Ireland",
  version: "0.1.0",
  instructions: "Tools for the Saunas in Ireland app. Use `list_saunas` and `find_nearest_sauna` to discover coastal saunas across Ireland, Wales, England, and Scotland. Use `get_home_sauna` and `set_home_sauna` to read or update the signed-in user's chosen home sauna.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_saunas_default,
    get_sauna_default,
    find_nearest_sauna_default,
    get_home_sauna_default,
    set_home_sauna_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
